blah:
  host: genesis.mongohq.com
  port: 27018
  adapter: mongodb
  database: deckapp
  username: true

development:
  host: localhost
  adapter: mongodb
  database: deckapp_dev

test:
  host: localhost
  adapter: mongodb
  database: deckapp_test

production:
  host: genesis.local.mongohq.com
  port: 27018
  adapter: mongodb
  database: deckapp
  username: true
